let countries = 
  [
    { code: "", name: "", disabled: "disabled" },
    { code: "Malaysia", name: "Malaysia", disabled: "" },
    { code: "Afghanistan", name: "Afghanistan", disabled: "" },
    { code: "Åland Islands", name: "Åland Islands", disabled: "" },
    { code: "Albania", name: "Albania", disabled: "" },
    { code: "Algeria", name: "Algeria", disabled: "" },
    { code: "American Samoa", name: "American Samoa", disabled: "" },
    { code: "Andorra", name: "Andorra", disabled: "" },
    { code: "Angola", name: "Angola", disabled: "" },
    { code: "Anguilla", name: "Anguilla", disabled: "" },
    { code: "Antarctica", name: "Antarctica", disabled: "" },
    { code: "Antigua and Barbuda", name: "Antigua and Barbuda", disabled: "" },
    { code: "Argentina", name: "Argentina", disabled: "" },
    { code: "Armenia", name: "Armenia", disabled: "" },
    { code: "Aruba", name: "Aruba", disabled: "" },
    { code: "Australia", name: "Australia", disabled: "" },
    { code: "Austria", name: "Austria", disabled: "" },
    { code: "Azerbaijan", name: "Azerbaijan", disabled: "" },
    { code: "Bahamas", name: "Bahamas", disabled: "" },
    { code: "Bahrain", name: "Bahrain", disabled: "" },
    { code: "Bangladesh", name: "Bangladesh", disabled: "" },
    { code: "Barbados", name: "Barbados", disabled: "" },
    { code: "Belarus", name: "Belarus", disabled: "" },
    { code: "Belgium", name: "Belgium", disabled: "" },
    { code: "Belize", name: "Belize", disabled: "" },
    { code: "Benin", name: "Benin", disabled: "" },
    { code: "Bermuda", name: "Bermuda", disabled: "" },
    { code: "Bhutan", name: "Bhutan", disabled: "" },
    { code: "Bolivia", name: "Bolivia", disabled: "" },
    { code: "Bonaire, Sint Eustatius and Saba", name: "Bonaire, Sint Eustatius and Saba", disabled: "" },
    { code: "Bosnia and Herzegovina", name: "Bosnia and Herzegovina", disabled: "" },
    { code: "Botswana", name: "Botswana", disabled: "" },
    { code: "Bouvet Island", name: "Bouvet Island", disabled: "" },
    { code: "Brazil", name: "Brazil", disabled: "" },
    { code: "British Indian Ocean Territory", name: "British Indian Ocean Territory", disabled: "" },
    { code: "Brunei Darussalam", name: "Brunei Darussalam", disabled: "" },
    { code: "Bulgaria", name: "Bulgaria", disabled: "" },
    { code: "Burkina Faso", name: "Burkina Faso", disabled: "" },
    { code: "Burundi", name: "Burundi", disabled: "" },
    { code: "Cabo Verde", name: "Cabo Verde", disabled: "" },
    { code: "Cambodia", name: "Cambodia", disabled: "" },
    { code: "Cameroon", name: "Cameroon", disabled: "" },
    { code: "Canada", name: "Canada", disabled: "" },
    { code: "Cayman Islands", name: "Cayman Islands", disabled: "" },
    { code: "Central African Republic", name: "Central African Republic", disabled: "" },
    { code: "Chad", name: "Chad", disabled: "" },
    { code: "Chile", name: "Chile", disabled: "" },
    { code: "China", name: "China", disabled: "" },
    { code: "Christmas Island", name: "Christmas Island", disabled: "" },
    { code: "Cocos (Keeling) Islands", name: "Cocos (Keeling) Islands", disabled: "" },
    { code: "Colombia", name: "Colombia", disabled: "" },
    { code: "Comoros", name: "Comoros", disabled: "" },
    { code: "Congo", name: "Congo", disabled: "" },
    { code: "Congo, The Democratic Republic of the", name: "Congo, The Democratic Republic of the", disabled: "" },
    { code: "Cook Islands", name: "Cook Islands", disabled: "" },
    { code: "Costa Rica", name: "Costa Rica", disabled: "" },
    { code: "Côte d'Ivoire", name: "Côte d'Ivoire", disabled: "" },
    { code: "Croatia", name: "Croatia", disabled: "" },
    { code: "Cuba", name: "Cuba", disabled: "" },
    { code: "Curaçao", name: "Curaçao", disabled: "" },
    { code: "Cyprus", name: "Cyprus", disabled: "" },
    { code: "Czechia", name: "Czechia", disabled: "" },
    { code: "Denmark", name: "Denmark", disabled: "" },
    { code: "Djibouti", name: "Djibouti", disabled: "" },
    { code: "Dominica", name: "Dominica", disabled: "" },
    { code: "Dominican Republic", name: "Dominican Republic", disabled: "" },
    { code: "Ecuador", name: "Ecuador", disabled: "" },
    { code: "Egypt", name: "Egypt", disabled: "" },
    { code: "El Salvador", name: "El Salvador", disabled: "" },
    { code: "Equatorial Guinea", name: "Equatorial Guinea", disabled: "" },
    { code: "Eritrea", name: "Eritrea", disabled: "" },
    { code: "Estonia", name: "Estonia", disabled: "" },
    { code: "Ethiopia", name: "Ethiopia", disabled: "" },
    { code: "Falkland Islands (Malvinas)", name: "Falkland Islands (Malvinas)", disabled: "" },
    { code: "Faroe Islands", name: "Faroe Islands", disabled: "" },
    { code: "Fiji", name: "Fiji", disabled: "" },
    { code: "Finland", name: "Finland", disabled: "" },
    { code: "France", name: "France", disabled: "" },
    { code: "French Guiana", name: "French Guiana", disabled: "" },
    { code: "French Polynesia", name: "French Polynesia", disabled: "" },
    { code: "French Southern Territories", name: "French Southern Territories", disabled: "" },
    { code: "Gabon", name: "Gabon", disabled: "" },
    { code: "Gambia", name: "Gambia", disabled: "" },
    { code: "Georgia", name: "Georgia", disabled: "" },
    { code: "Germany", name: "Germany", disabled: "" },
    { code: "Ghana", name: "Ghana", disabled: "" },
    { code: "Gibraltar", name: "Gibraltar", disabled: "" },
    { code: "Greece", name: "Greece", disabled: "" },
    { code: "Greenland", name: "Greenland", disabled: "" },
    { code: "Grenada", name: "Grenada", disabled: "" },
    { code: "Guadeloupe", name: "Guadeloupe", disabled: "" },
    { code: "Guam", name: "Guam", disabled: "" },
    { code: "Guatemala", name: "Guatemala", disabled: "" },
    { code: "Guernsey", name: "Guernsey", disabled: "" },
    { code: "Guinea", name: "Guinea", disabled: "" },
    { code: "Guinea-Bissau", name: "Guinea-Bissau", disabled: "" },
    { code: "Guyana", name: "Guyana", disabled: "" },
    { code: "Haiti", name: "Haiti", disabled: "" },
    { code: "Heard Island and McDonald Islands", name: "Heard Island and McDonald Islands", disabled: "" },
    { code: "Holy See (Vatican City State)", name: "Holy See (Vatican City State)", disabled: "" },
    { code: "Honduras", name: "Honduras", disabled: "" },
    { code: "Hong Kong", name: "Hong Kong", disabled: "" },
    { code: "Hungary", name: "Hungary", disabled: "" },
    { code: "Iceland", name: "Iceland", disabled: "" },
    { code: "India", name: "India", disabled: "" },
    { code: "Indonesia", name: "Indonesia", disabled: "" },
    { code: "Iran, Islamic Republic of", name: "Iran, Islamic Republic of", disabled: "" },
    { code: "Iraq", name: "Iraq", disabled: "" },
    { code: "Ireland", name: "Ireland", disabled: "" },
    { code: "Isle of Man", name: "Isle of Man", disabled: "" },
    { code: "Israel", name: "Israel", disabled: "" },
    { code: "Italy", name: "Italy", disabled: "" },
    { code: "Jamaica", name: "Jamaica", disabled: "" },
    { code: "Japan", name: "Japan", disabled: "" },
    { code: "Jersey", name: "Jersey", disabled: "" },
    { code: "Jordan", name: "Jordan", disabled: "" },
    { code: "Kazakhstan", name: "Kazakhstan", disabled: "" },
    { code: "Kenya", name: "Kenya", disabled: "" },
    { code: "Kiribati", name: "Kiribati", disabled: "" },
    { code: "Korea, Democratic People's Republic of", name: "Korea, Democratic People's Republic of", disabled: "" },
    { code: "Korea, Republic of", name: "Korea, Republic of", disabled: "" },
    { code: "Kuwait", name: "Kuwait", disabled: "" },
    { code: "Kyrgyzstan", name: "Kyrgyzstan", disabled: "" },
    { code: "Lao People's Democratic Republic", name: "Lao People's Democratic Republic", disabled: "" },
    { code: "Latvia", name: "Latvia", disabled: "" },
    { code: "Lebanon", name: "Lebanon", disabled: "" },
    { code: "Lesotho", name: "Lesotho", disabled: "" },
    { code: "Liberia", name: "Liberia", disabled: "" },
    { code: "Libya", name: "Libya", disabled: "" },
    { code: "Liechtenstein", name: "Liechtenstein", disabled: "" },
    { code: "Lithuania", name: "Lithuania", disabled: "" },
    { code: "Luxembourg", name: "Luxembourg", disabled: "" },
    { code: "Macao", name: "Macao", disabled: "" },
    { code: "Macedonia, Republic of", name: "Macedonia, Republic of", disabled: "" },
    { code: "Madagascar", name: "Madagascar", disabled: "" },
    { code: "Malawi", name: "Malawi", disabled: "" },
    { code: "Malaysia", name: "Malaysia", disabled: "" },
    { code: "Maldives", name: "Maldives", disabled: "" },
    { code: "Mali", name: "Mali", disabled: "" },
    { code: "Malta", name: "Malta", disabled: "" },
    { code: "Marshall Islands", name: "Marshall Islands", disabled: "" },
    { code: "Martinique", name: "Martinique", disabled: "" },
    { code: "Mauritania", name: "Mauritania", disabled: "" },
    { code: "Mauritius", name: "Mauritius", disabled: "" },
    { code: "Mayotte", name: "Mayotte", disabled: "" },
    { code: "Mexico", name: "Mexico", disabled: "" },
    { code: "Micronesia, Federated States of", name: "Micronesia, Federated States of", disabled: "" },
    { code: "Moldova", name: "Moldova", disabled: "" },
    { code: "Monaco", name: "Monaco", disabled: "" },
    { code: "Mongolia", name: "Mongolia", disabled: "" },
    { code: "Montenegro", name: "Montenegro", disabled: "" },
    { code: "Montserrat", name: "Montserrat", disabled: "" },
    { code: "Morocco", name: "Morocco", disabled: "" },
    { code: "Mozambique", name: "Mozambique", disabled: "" },
    { code: "Myanmar", name: "Myanmar", disabled: "" },
    { code: "Namibia", name: "Namibia", disabled: "" },
    { code: "Nauru", name: "Nauru", disabled: "" },
    { code: "Nepal", name: "Nepal", disabled: "" },
    { code: "Netherlands", name: "Netherlands", disabled: "" },
    { code: "New Caledonia", name: "New Caledonia", disabled: "" },
    { code: "New Zealand", name: "New Zealand", disabled: "" },
    { code: "Nicaragua", name: "Nicaragua", disabled: "" },
    { code: "Niger", name: "Niger", disabled: "" },
    { code: "Nigeria", name: "Nigeria", disabled: "" },
    { code: "Niue", name: "Niue", disabled: "" },
    { code: "Norfolk Island", name: "Norfolk Island", disabled: "" },
    { code: "Northern Mariana Islands", name: "Northern Mariana Islands", disabled: "" },
    { code: "Norway", name: "Norway", disabled: "" },
    { code: "Oman", name: "Oman", disabled: "" },
    { code: "Pakistan", name: "Pakistan", disabled: "" },
    { code: "Palau", name: "Palau", disabled: "" },
    { code: "Palestine, State of", name: "Palestine, State of", disabled: "" },
    { code: "Panama", name: "Panama", disabled: "" },
    { code: "Papua New Guinea", name: "Papua New Guinea", disabled: "" },
    { code: "Paraguay", name: "Paraguay", disabled: "" },
    { code: "Peru", name: "Peru", disabled: "" },
    { code: "Philippines", name: "Philippines", disabled: "" },
    { code: "Pitcairn", name: "Pitcairn", disabled: "" },
    { code: "Poland", name: "Poland", disabled: "" },
    { code: "Portugal", name: "Portugal", disabled: "" },
    { code: "Puerto Rico", name: "Puerto Rico", disabled: "" },
    { code: "Qatar", name: "Qatar", disabled: "" },
    { code: "Réunion", name: "Réunion", disabled: "" },
    { code: "Romania", name: "Romania", disabled: "" },
    { code: "Russian Federation", name: "Russian Federation", disabled: "" },
    { code: "Rwanda", name: "Rwanda", disabled: "" },
    { code: "Saint Barthélemy", name: "Saint Barthélemy", disabled: "" },
    { code: "Saint Helena, Ascension and Tristan da Cunha", name: "Saint Helena, Ascension and Tristan da Cunha", disabled: "" },
    { code: "Saint Kitts and Nevis", name: "Saint Kitts and Nevis", disabled: "" },
    { code: "Saint Lucia", name: "Saint Lucia", disabled: "" },
    { code: "Saint Martin (French part)", name: "Saint Martin (French part)", disabled: "" },
    { code: "Saint Pierre and Miquelon", name: "Saint Pierre and Miquelon", disabled: "" },
    { code: "Saint Vincent and the Grenadines", name: "Saint Vincent and the Grenadines", disabled: "" },
    { code: "Samoa", name: "Samoa", disabled: "" },
    { code: "San Marino", name: "San Marino", disabled: "" },
    { code: "Sao Tome and Principe", name: "Sao Tome and Principe", disabled: "" },
    { code: "Saudi Arabia", name: "Saudi Arabia", disabled: "" },
    { code: "Senegal", name: "Senegal", disabled: "" },
    { code: "Serbia", name: "Serbia", disabled: "" },
    { code: "Seychelles", name: "Seychelles", disabled: "" },
    { code: "Sierra Leone", name: "Sierra Leone", disabled: "" },
    { code: "Singapore", name: "Singapore", disabled: "" },
    { code: "Sint Maarten (Dutch part)", name: "Sint Maarten (Dutch part)", disabled: "" },
    { code: "Slovakia", name: "Slovakia", disabled: "" },
    { code: "Slovenia", name: "Slovenia", disabled: "" },
    { code: "Solomon Islands", name: "Solomon Islands", disabled: "" },
    { code: "Somalia", name: "Somalia", disabled: "" },
    { code: "South Africa", name: "South Africa", disabled: "" },
    { code: "South Georgia and the South Sandwich Islands", name: "South Georgia and the South Sandwich Islands", disabled: "" },
    { code: "South Sudan", name: "South Sudan", disabled: "" },
    { code: "Spain", name: "Spain", disabled: "" },
    { code: "Sri Lanka", name: "Sri Lanka", disabled: "" },
    { code: "Sudan", name: "Sudan", disabled: "" },
    { code: "Suriname", name: "Suriname", disabled: "" },
    { code: "Svalbard and Jan Mayen", name: "Svalbard and Jan Mayen", disabled: "" },
    { code: "Swaziland", name: "Swaziland", disabled: "" },
    { code: "Sweden", name: "Sweden", disabled: "" },
    { code: "Switzerland", name: "Switzerland", disabled: "" },
    { code: "Syrian Arab Republic", name: "Syrian Arab Republic", disabled: "" },
    { code: "Taiwan", name: "Taiwan", disabled: "" },
    { code: "Tajikistan", name: "Tajikistan", disabled: "" },
    { code: "Tanzania", name: "Tanzania", disabled: "" },
    { code: "Thailand", name: "Thailand", disabled: "" },
    { code: "Timor-Leste", name: "Timor-Leste", disabled: "" },
    { code: "Togo", name: "Togo", disabled: "" },
    { code: "Tokelau", name: "Tokelau", disabled: "" },
    { code: "Tonga", name: "Tonga", disabled: "" },
    { code: "Trinidad and Tobago", name: "Trinidad and Tobago", disabled: "" },
    { code: "Tunisia", name: "Tunisia", disabled: "" },
    { code: "Turkey", name: "Turkey", disabled: "" },
    { code: "Turkmenistan", name: "Turkmenistan", disabled: "" },
    { code: "Turks and Caicos Islands", name: "Turks and Caicos Islands", disabled: "" },
    { code: "Tuvalu", name: "Tuvalu", disabled: "" },
    { code: "Uganda", name: "Uganda", disabled: "" },
    { code: "Ukraine", name: "Ukraine", disabled: "" },
    { code: "United Arab Emirates", name: "United Arab Emirates", disabled: "" },
    { code: "United Kingdom", name: "United Kingdom", disabled: "" },
    { code: "United States Minor Outlying Islands", name: "United States Minor Outlying Islands", disabled: "" },
    { code: "United States", name: "United States", disabled: "" },
    { code: "Uruguay", name: "Uruguay", disabled: "" },
    { code: "Uzbekistan", name: "Uzbekistan", disabled: "" },
    { code: "Vanuatu", name: "Vanuatu", disabled: "" },
    { code: "Venezuela", name: "Venezuela", disabled: "" },
    { code: "Vietnam", name: "Vietnam", disabled: "" },
    { code: "Virgin Islands, British", name: "Virgin Islands, British", disabled: "" },
    { code: "Virgin Islands, U.S.", name: "Virgin Islands, U.S.", disabled: "" },
    { code: "Wallis and Futuna", name: "Wallis and Futuna", disabled: "" },
    { code: "Western Sahara", name: "Western Sahara", disabled: "" },
    { code: "Yemen", name: "Yemen", disabled: "" },
    { code: "Zambia", name: "Zambia", disabled: "" },
    { code: "Zimbabwe", name: "Zimbabwe", disabled: "" }
  ]

let options = countries.map(country => `<option value="${country.code}" ${country.disabled}>${country.name}</option>`).join('\n');
let lastDirectorSelect, directorCountrySelect, directorCountrySelectLast;
function mapDirectorCountrySelect() {
  directorCountrySelect = document.querySelectorAll('select[data-select-type="director-country"]');
  lastDirectorSelect = directorCountrySelect.length - 1;
  directorCountrySelectLast = directorCountrySelect[lastDirectorSelect];
  directorCountrySelectLast.innerHTML = options;
}
mapDirectorCountrySelect();