let msic = 
[
  { placeholder: true, text: "Select MSIC Code(s)" },
  { text: "01111 - Growing of maize" },
  { text: "01112 - Growing of leguminous crops" },
  { text: "01113 - Growing of oil seeds" },
  { text: "01119 - Growing of other cereals n.e.c." },
  { text: "01120 - Growing of paddy" },
  { text: "01131 - Growing of leafy or stem vegetables" },
  { text: "01132 - Growing of fruits bearing vegetables" },
  { text: "01133 - Growing of melons" },
  { text: "01134 - Growing of mushrooms and truffles" },
  { text: "01135 - Growing of vegetables seeds, except beet seeds" },
  { text: "01136 - Growing of other vegetables" },
  { text: "01137 - Growing of sugar beet" },
  { text: "01138 - Growing of roots, tubers, bulb or tuberous vegetables" },
  { text: "01140 - Growing of sugar cane" },
  { text: "01150 - Growing of tobacco" },
  { text: "01160 - Growing of fibre crops" },
  { text: "01191 - Growing of flowers" },
  { text: "01192 - Growing of flower seeds" },
  { text: "01193 - Growing of sago (rumbia)" },
  { text: "01199 - Growing of other non-perennial crops n.e.c." },
  { text: "01210 - Growing of grapes" },
  { text: "01221 - Growing of banana" },
  { text: "01222 - Growing of mango" },
  { text: "01223 - Growing of durian" },
  { text: "01224 - Growing of rambutan" },
  { text: "01225 - Growing of star fruit" },
  { text: "01226 - Growing of papaya" },
  { text: "01227 - Growing of pineapple" },
  { text: "01228 - Growing of pitaya (dragon fruit)" },
  { text: "01229 - Growing of other tropical and subtropical fruits n.e.c." },
  { text: "01231 - Growing of pomelo" },
  { text: "01232 - Growing of lemon and limes" },
  { text: "01233 - Growing of tangerines and mandarin" },
  { text: "01239 - Growing of other citrus fruits n.e.c." },
  { text: "01241 - Growing of guava" },
  { text: "01249 - Growing of other pome fruits and stones fruits n.e.c." },
  { text: "01251 - Growing of berries" },
  { text: "01252 - Growing of fruit seeds" },
  { text: "01253 - Growing of edible nuts" },
  { text: "01259 - Growing of other tree and bush fruits" },
  { text: "01261 - Growing of oil palm (estate)" },
  { text: "01262 - Growing of oil palm (smallholdings)" },
  { text: "01263 - Growing of coconut (estate and smallholdings)" },
  { text: "01269 - Growing of other oleaginous fruits n.e.c." },
  { text: "01271 - Growing of coffee" },
  { text: "01272 - Growing of tea" },
  { text: "01273 - Growing of cocoa" },
  { text: "01279 - Growing of other beverage crops n.e.c." },
  { text: "01281 - Growing of pepper (piper nigrum)" },
  { text: "01282 - Growing of chilies and pepper (capsicum spp.)" },
  { text: "01283 - Growing of nutmeg" },
  { text: "01284 - Growing of ginger" },
  { text: "01285 - Growing of plants used primarily in perfumery, in pharmacy or for insecticidal, fungicidal or similar purposes" },
  { text: "01289 - Growing of other spices and aromatic crops n.e.c." },
  { text: "01291 - Growing of rubber trees (estate)" },
  { text: "01292 - Growing of rubber trees (smallholdings)" },
  { text: "01293 - Growing of trees for extraction of sap" },
  { text: "01294 - Growing of nipa palm" },
  { text: "01295 - Growing of areca" },
  { text: "01296 - Growing of roselle" },
  { text: "01299 - Growing of other perennial crops n.e.c." },
  { text: "01301 - Growing of plants for planting" },
  { text: "01302 - Growing of plants for ornamental purposes" },
  { text: "01303 - Growing of live plants for bulbs, tubers and roots; cuttings and slips; mushroom spawn" },
  { text: "01304 - Operation of tree nurseries" },
  { text: "01411 - Raising, breeding and production of cattle or buffaloes" },
  { text: "01412 - Production of raw milk from cows or buffaloes" },
  { text: "01413 - Production of bovine semen" },
  { text: "01420 - Raising and breeding of horses, asses, mules or hinnes" },
  { text: "01430 - Raising and breeding of camels (dromedary) and camelids" },
  { text: "01441 - Raising, breeding and production of sheep and goats" },
  { text: "01442 - Production of raw sheep or goat’s milk" },
  { text: "01443 - Production of raw wool" },
  { text: "01450 - Raising, breeding and production of swine/pigs" },
  { text: "01461 - Raising, breeding and production of chicken, broiler" },
  { text: "01462 - Raising, breeding and production of ducks" },
  { text: "01463 - Raising, breeding and production of geese" },
  { text: "01464 - Raising, breeding and production of quails" },
  { text: "01465 - Raising and breeding of other poultry n.e.c." },
  { text: "01466 - Production of chicken eggs" },
  { text: "01467 - Production of duck eggs" },
  { text: "01468 - Production of other poultry eggs n.e.c." },
  { text: "01469 - Operation of poultry hatcheries" },
  { text: "01491 - Raising, breeding and production of semi-domesticated" },
  { text: "01492 - Production of fur skins, reptile or bird’s skin from ranching operation" },
  { text: "01493 - Operation of worm farms, land mollusc farms, snail farms" },
  { text: "01494 - Raising of silk worms and production of silk worm cocoons" },
  { text: "01495 - Bee keeping and production of honey and beeswax" },
  { text: "01496 - Raising and breeding of pet animals" },
  { text: "01497 - Raising and breeding of swiflet" },
  { text: "01499 - Raising of diverse/other animals n.e.c." },
  { text: "01500 - Mixed Farming" },
  { text: "01610 - Agricultural activities for crops production on a fee or contract basis" },
  { text: "01620 - Agricultural activities for animal production on a fee or contract basis" },
  { text: "01631 - Preparation of crops for primary markets" },
  { text: "01632 - Preparation of tobacco leaves" },
  { text: "01633 - Preparation of cocoa beans" },
  { text: "01634 - Sun-drying of fruits and vegetables" },
  { text: "01640 - Seed processing for propagation" },
  { text: "01701 - Hunting and trapping on a commercial basis" },
  { text: "01702 - Taking of animals (dead or alive)" },
  { text: "02101 - Planting, replanting, transplanting, thinning and conserving of forests and timber tracts" },
  { text: "02102 - Growing of coppice, pulpwood and fire wood" },
  { text: "02103 - Operation of forest tree nurseries" },
  { text: "02104 - Collection and raising of wildings (peat swamp forest tree species)" },
  { text: "02105 - Forest plantation" },
  { text: "02201 - Production of round wood for forest-based manufacturing industries" },
  { text: "02202 - Production of round wood used in an unprocessed form" },
  { text: "02203 - Production of charcoal in the forest (using traditional methods)" },
  { text: "02204 - Rubber wood logging" },
  { text: "02301 - Collection of rattan, bamboo" },
  { text: "02302 - Bird’s nest collection" },
  { text: "02303 - Wild sago palm collection" },
  { text: "02309 - Gathering of non-wood forest products n.e.c." },
  { text: "02401 - Carrying out part of the forestry and forest plantation operation on a fee or contract basis for forestry service activities" },
  { text: "02402 - Carrying out part of the forestry operation on a fee or contract basis for logging service activities" },
  { text: "03111 - Fishing on a commercial basis in ocean and coastal waters" },
  { text: "03112 - Collection of marine crustaceans and molluscs" },
  { text: "03113 - Taking of aquatic animals: sea squirts, tunicates, sea urchins" },
  { text: "03114 - Activities of vessels engaged both in fishing and in processing and preserving offish" },
  { text: "03115 - Gathering of other marine organisms and materials (natural pearls, sponges, coral and algae)" },
  { text: "03119 - Marine fishing n.e.c." },
  { text: "03121 - Fishing on a commercial basis in inland waters" },
  { text: "03122 - Taking of freshwater crustaceans and molluscs" },
  { text: "03123 - Taking of freshwater aquatic animals" },
  { text: "03124 - Gathering of freshwater flora and fauna" },
  { text: "03129 - Freshwater fishing n.e.c." },
  { text: "03211 - Fish farming in sea water" },
  { text: "03212 - Production of bivalve spat (oyster, mussel), lobster lings, shrimp post-larvae, fish fry and fingerlings" },
  { text: "03213 - Growing of laver and other edible seaweeds" },
  { text: "03214 - Culture of crustaceans, bivalves, other molluscs and other aquatic animals in sea water" },
  { text: "03215 - Aquaculture activities in brackish water" },
  { text: "03216 - Aquaculture activities in salt water filled tanks or reservoirs" },
  { text: "03217 - Operation of hatcheries (marine)" },
  { text: "03218 - Operation of marine worm farms for fish feed" },
  { text: "03219 - Marine aquaculture n.e.c." },
  { text: "03221 - Fish farming in freshwater" },
  { text: "03222 - Shrimp farming in freshwater" },
  { text: "03223 - Culture of freshwater crustaceans, bivalves, other molluscs and other aquatic animals" },
  { text: "03224 - Operation of hatcheries (freshwater)" },
  { text: "03225 - Farming of frogs" },
  { text: "03229 - Freshwater aquaculture n.e.c." },
  { text: "05100 - Mining of hard coal" },
  { text: "05200 - Mining of lignite (brown coal)" },
  { text: "06101 - Extraction of crude petroleum oils" },
  { text: "06102 - Extraction of bituminous or oil shale and tar sand" },
  { text: "06103 - Production of crude petroleum from bituminous shale and sand" },
  { text: "06104 - Processes to obtain crude oils" },
  { text: "06201 - Production of crude gaseous hydrocarbon (natural gas)" },
  { text: "06202 - Extraction of condensates" },
  { text: "06203 - Draining and separation of liquid hydrocarbon fractions" },
  { text: "06204 - Gas desulphurization" },
  { text: "06205 - Mining of hydrocarbon liquids, obtain through liquefaction or pyrolysis" },
  { text: "07101 - Mining of ores valued chiefly for iron content" },
  { text: "07102 - Beneficiation and agglomeration of iron ores" },
  { text: "07210 - Mining of uranium and thorium ores" },
  { text: "07291 - Mining of tin ores" },
  { text: "07292 - Mining of copper" },
  { text: "07293 - Mining of bauxite (aluminium)" },
  { text: "07294 - Mining of ilmenite" },
  { text: "07295 - Mining of gold" },
  { text: "07296 - Mining of silver" },
  { text: "07297 - Mining of platinum" },
  { text: "07298 - Am a ng retreatment" },
  { text: "07299 - Mining of other non-ferrous metal ores n.e.c." },
  { text: "08101 - Quarrying, rough trimming and sawing of monumental and building stone such as marble, granite (dimension stone), sandstone" },
  { text: "08102 - Quarrying, crushing and breaking of limestone" },
  { text: "08103 - Mining of gypsum and anhydrite" },
  { text: "08104 - Mining of chalk and uncalcined dolomite" },
  { text: "08105 - Extraction and dredging of industrial sand, sand for construction and gravel" },
  { text: "08106 - Breaking and crushing of stone and gravel" },
  { text: "08107 - Quarrying of sand" },
  { text: "08108 - Mining of clays, refractory clays and kaolin" },
  { text: "08109 - Quarrying, crushing and breaking of granite" },
  { text: "08911 - Mining of natural phosphates" },
  { text: "08912 - Mining of natural potassium salts" },
  { text: "08913 - Mining of native sulphur" },
  { text: "08914 - Extraction and preparation of pyrites and pyrrhotite, except roasting" },
  { text: "08915 - Mining of natural barium sulphate and carbonate (barytes and witherite)" },
  { text: "08916 - Mining of natural borates, natural magnesium sulphates (kieserite)" },
  { text: "08917 - Mining of earth colours, fluorspar and other minerals valued chiefly as a source of chemicals" },
  { text: "08918 - Guano mining" },
  { text: "08921 - Peat digging" },
  { text: "08922 - Peat agglomeration" },
  { text: "08923 - Preparation of peat to improve quality or facilitate transport or storage" },
  { text: "08931 - Extraction of salt from underground" },
  { text: "08932 - Salt production by evaporation of sea water or other saline waters" },
  { text: "08933 - Crushing, purification and refining of salt by the producer" },
  { text: "08991 - Mining and quarrying of abrasive materials" },
  { text: "08992 - Mining and quarrying of asbestos" },
  { text: "08993 - Mining and quarrying of siliceous fossil meals" },
  { text: "08994 - Mining and quarrying of natural graphite" },
  { text: "08995 - Mining and quarrying of steatite (talc)" },
  { text: "08996 - Mining and quarrying of gemstones" },
  { text: "08999 - Other mining and quarrying n.e.c." },
  { text: "09101 - Oil and gas extraction service activities provided on a fee or contract basis" },
  { text: "09102 - Oil and gas field fire fighting services" },
  { text: "09900 - Support activities for other mining and quarrying" },
  { text: "10101 - Processing and preserving of meat and production of meat products" },
  { text: "10102 - Processing and preserving of poultry and poultry products" },
  { text: "10103 - Production of hides and skins originating from slaughterhouses" },
  { text: "10104 - Operation of slaughterhouses engaged in killing, houses dressing or packing meat" },
  { text: "10109 - Processing and preserving of meat n.e.c." },
  { text: "10201 - Canning offish, crustaceans and mollusks" },
  { text: "10202 - Processing, curing and preserving offish, crustacean and molluscs" },
  { text: "10203 - Production offish meals for human consumption or animal feed" },
  { text: "10204 - Production of keropok including keropok lekor" },
  { text: "10205 - Processing of seaweed" },
  { text: "10301 - Manufacture of fruits and vegetable food products" },
  { text: "10302 - Manufacture of fruit and vegetable juices" },
  { text: "10303 - Pineapple canning" },
  { text: "10304 - Manufacture of jams, marmalades and table jellies" },
  { text: "10305 - Manufacture of nuts and nut products" },
  { text: "10306 - Manufacture of bean curd products" },
  { text: "10401 - Manufacture of crude palm oil" },
  { text: "10402 - Manufacture of refined palm oil" },
  { text: "10403 - Manufacture of palm kernel oil" },
  { text: "10404 - Manufacture of crude and refined vegetable oil" },
  { text: "10405 - Manufacture of coconut oil" },
  { text: "10406 - Manufacture of compound cooking fats" },
  { text: "10407 - Manufacture of animal oils and fats" },
  { text: "10501 - Manufacture of ice cream and other edible ice such as sorbet" },
  { text: "10502 - Manufacture of condensed, powdered and evaporated milk" },
  { text: "10509 - Manufacture of other dairy products n.e.c." },
  { text: "10611 - Rice milling" },
  { text: "10612 - Provision of milling services" },
  { text: "10613 - Flour milling" },
  { text: "10619 - Manufacture of grain mill products n.e.c." },
  { text: "10621 - Manufacture of starches and starch products" },
  { text: "10622 - Manufacture of glucose, glucose syrup, maltose, inulin" },
  { text: "10623 - Manufacture of sago and tapioca flour/products" },
  { text: "10711 - Manufacture of biscuits and cookies" },
  { text: "10712 - Manufacture of bread, cakes and other bakery products" },
  { text: "10713 - Manufacture of snack products" },
  { text: "10714 - Manufacture of frozen bakery products" },
  { text: "10721 - Manufacture of sugar" },
  { text: "10722 - Manufacture of sugar products" },
  { text: "10731 - Manufacture of cocoa products" },
  { text: "10732 - Manufacture of chocolate and chocolate products" },
  { text: "10733 - Manufacture of sugar confectionery" },
  { text: "10741 - Manufacture of meehoon, noodles and other related products" },
  { text: "10742 - Manufacture of pastas" },
  { text: "10750 - Manufacture of prepared meals and dishes" },
  { text: "10791 - Manufacture of coffee" },
  { text: "10792 - Manufacture of tea" },
  { text: "10793 - Manufacture of sauces and condiments" },
  { text: "10794 - Manufacture of spices and curry powder" },
  { text: "10795 - Manufacture of egg products" },
  { text: "10799 - Manufacture of other food products n.e.c." },
  { text: "10800 - Manufacture of prepared animal feeds" },
  { text: "11010 - Distilling, rectifying and blending of spirits" },
  { text: "11020 - Manufacture of wines" },
  { text: "11030 - Manufacture of malt liquors and malt" },
  { text: "11041 - Manufacture of soft drinks" },
  { text: "11042 - Production of natural mineral water and other bottled water" },
  { text: "13110 - Preparation and spinning of textile fibres" },
  { text: "13120 - Weaving of textiles" },
  { text: "13131 - Batik making" },
  { text: "13132 - Dyeing, bleaching, printing and finishing of yarns and fabrics" },
  { text: "13139 - Other finishing textiles" },
  { text: "13910 - Manufacture of knitted and crocheted fabrics" },
  { text: "13921 - Manufacture of made-up articles of any textile materials, including of knitted or crocheted fabrics" },
  { text: "13922 - Manufacture of made-up furnishing articles" },
  { text: "13930 - Manufacture of carpets and rugs" },
  { text: "13940 - Manufacture of cordage, rope, twine and netting" },
  { text: "13990 - Manufacture of other textiles n.e.c." },
  { text: "14101 - Manufacture of specific wearing apparel" },
  { text: "14102 - Manufacture of clothings" },
  { text: "14103 - Custom tailoring" },
  { text: "14109 - Manufacture of other clothing accessories" },
  { text: "14200 - Manufacture of articles made of fur skins" },
  { text: "14300 - Manufacture of knitted and crocheted apparel" },
  { text: "15110 - Tanning and dressing of leather; dressing and dyeing of fur" },
  { text: "15120 - Manufacture of luggage, handbags and the like, saddlery and harness" },
  { text: "15201 - Manufacture of leather footwear" },
  { text: "15202 - Manufacture of plastic footwear" },
  { text: "15203 - Manufacture of rubber footwear" },
  { text: "15209 - Manufacture of other footwear n.e.c." },
  { text: "16100 - Sawmilling and planning of wood" },
  { text: "16211 - Manufacture of veneer sheets and plywood" },
  { text: "16212 - Manufacture of particle board and fibreboard" },
  { text: "16221 - Manufacture of builders' carpentry" },
  { text: "16222 - Manufacture of joinery wood products" },
  { text: "16230 - Manufacture of wooden containers" },
  { text: "16291 - Manufacture of wood charcoal" },
  { text: "16292 - Manufacture of other products of wood, cane, articles of cork, straw and plaiting materials" },
  { text: "17010 - Manufacture of pulp, paper and paperboard" },
  { text: "17020 - Manufacture of corrugated paper and paperboard and of containers of paper and paperboard" },
  { text: "17091 - Manufacture of envelopes and letter-card" },
  { text: "17092 - Manufacture of household and personal hygiene paper" },
  { text: "17093 - Manufacture of gummed or adhesive paper in strips or rolls and labels and wall paper" },
  { text: "17094 - Manufacture of effigies, funeral paper goods, joss paper" },
  { text: "17099 - Manufacture of other articles of paper and paperboard n.e.c." },
  { text: "18110 - Printing" },
  { text: "18120 - Service activities related to printing" },
  { text: "18200 - Reproduction of recorded media" },
  { text: "19100 - Manufacture of coke oven products" },
  { text: "19201 - Manufacture of refined petroleum products" },
  { text: "19202 - Manufacture of bio-diesel products" },
  { text: "20111 - Manufacture of liquefied or compressed inorganic industrial or medical gases" },
  { text: "20112 - Manufacture of basic organic chemicals" },
  { text: "20113 - Manufacture of inorganic compounds" },
  { text: "20119 - Manufacture of other basic chemicals n.e.c." },
  { text: "20121 - Manufacture of fertilizers" },
  { text: "20129 - Manufacture of associated nitrogen products" },
  { text: "20131 - Manufacture of plastic in primary forms" },
  { text: "20132 - Manufacture of synthetic rubber in primary forms: synthetic rubber, factice" },
  { text: "20133 - Manufacture of mixtures of synthetic rubber and natural rubber or rubber - like gums" },
  { text: "20210 - Manufacture of pesticides and other agrochemical products" },
  { text: "20221 - Manufacture of paints, varnishes and similar coatings ink and mastics" },
  { text: "20222 - Manufacture of printing ink" },
  { text: "20231 - Manufacture of soap and detergents, cleaning and polishing preparations" },
  { text: "20232 - Manufacture of perfumes and toilet preparations" },
  { text: "20291 - Manufacture of photographic plates, films, sensitized paper and other sensitized unexposed materials" },
  { text: "20292 - Manufacture of writing and drawing ink" },
  { text: "20299 - Manufacture of other chemical products n.e.c." },
  { text: "20300 - Manufacture of man-made fibres" },
  { text: "21001 - Manufacture of medicinal active substances to be used fortheir pharmacological properties in the manufacture of medicaments" },
  { text: "21002 - Processing of blood" },
  { text: "21003 - Manufacture of medicaments" },
  { text: "21004 - Manufacture of chemical contraceptive products" },
  { text: "21005 - Manufacture of medical diagnostic preparation" },
  { text: "21006 - Manufacture of radioactive in-vivo diagnostic substances" },
  { text: "21007 - Manufacture of biotech pharmaceuticals" },
  { text: "21009 - Manufacture of other pharmaceuticals, medicinal chemical and botanical products n.e.c." },
  { text: "22111 - Manufacture of rubber tyres for vehicles" },
  { text: "22112 - Manufacture of interchangeable tyre treads and retreading rubber tyres" },
  { text: "22191 - Manufacture of other products of natural or synthetic rubber, unvulcanized, vulcanized or hardened" },
  { text: "22192 - Manufacture of rubber gloves" },
  { text: "22193 - Rubber remilling and latex processing" },
  { text: "22199 - Manufacture of other rubber products n.e.c" },
  { text: "22201 - Manufacture of semi-manufactures of plastic products" },
  { text: "22202 - Manufacture of finished plastic products" },
  { text: "22203 - Manufacture of plastic articles for the packing of goods" },
  { text: "22204 - Manufacture of builders' plastics ware" },
  { text: "22205 - Manufacture of plastic tableware, kitchenware and toilet articles" },
  { text: "22209 - Manufacture of diverse plastic products n.e.c." },
  { text: "23101 - Manufacture of flat glass, including wired, coloured or tinted flat glass" },
  { text: "23102 - Manufacture of laboratory, hygienic or pharmaceutical glassware" },
  { text: "23109 - Manufacture of other glass products n.e.c." },
  { text: "23911 - Manufacture of refractory mortars and concretes" },
  { text: "23912 - Manufacture of refractory ceramic goods" },
  { text: "23921 - Manufacture of non-refractory ceramic" },
  { text: "23929 - Manufacture of other clay building materials" },
  { text: "23930 - Manufacture of other porcelain and ceramic products" },
  { text: "23941 - Manufacture of hydraulic cement" },
  { text: "23942 - Manufacture of lime and plaster" },
  { text: "23951 - Manufacture of ready-mix and dry-mix concrete and mortars" },
  { text: "23952 - Manufacture of precast concrete, cement or artificial stone articles for use in construction" },
  { text: "23953 - Manufacture of prefabricated structural components for building or civil engineering of cement, concrete or artificial stone" },
  { text: "23959 - Manufacture of other articles of concrete, cement and plaster n.e.c." },
  { text: "23960 - Cutting, shaping and finishing of stone" },
  { text: "23990 - Manufacture of other non-metallic mineral products n.e.c." },
  { text: "24101 - Production of pig iron and spiegeleisen in pigs, blocks or other primary forms" },
  { text: "24102 - Production of bars and rods of stainless steel or other alloy steel" },
  { text: "24103 - Manufacture of seamless tubes, by hot rolling, hot extrusion or hot drawing, or by cold drawing or cold rolling" },
  { text: "24104 - Manufacture of steel tube fittings" },
  { text: "24109 - Manufacture of other basic iron and steel products n.e.c." },
  { text: "24201 - Tin smelting" },
  { text: "24202 - Production of aluminium from alumina" },
  { text: "24209 - Manufacture of other basic precious and other non-ferrous metals n.e.c." },
  { text: "24311 - Casting of iron" },
  { text: "24312 - Casting of steel" },
  { text: "24320 - Casting of non-ferrous metals" },
  { text: "25111 - Manufacture of industrial frameworks in metal" },
  { text: "25112 - Manufacture of prefabricated buildings mainly of metal" },
  { text: "25113 - Manufacture of metal doors, windows and their frames, shutters and gates" },
  { text: "25119 - Manufacture of other structural metal products" },
  { text: "25120 - Manufacture of tanks, reservoirs and containers of metal" },
  { text: "25130 - Manufacture of steam generators, except central heating hot water boilers" },
  { text: "25200 - Manufacture of weapons and ammunition" },
  { text: "25910 - Forging, pressing, stamping and roll-forming of metal; powder metallurgy" },
  { text: "25920 - Treatment and coating of metals; machining" },
  { text: "25930 - Manufacture of cutlery, hand tools and general hardware" },
  { text: "25991 - Manufacture of tins and cans for food products, collapsible tubes and boxes" },
  { text: "25992 - Manufacture of metal cable, plaited bands and similar articles" },
  { text: "25993 - Manufacture of bolts, screws, nuts and similar threaded products" },
  { text: "25994 - Manufacture of metal household articles" },
  { text: "25999 - Manufacture of any other fabricated metal products n.e.c." },
  { text: "26101 - Manufacture of diodes, transistors and similar semiconductor devices" },
  { text: "26102 - Manufacture electronic integrated circuits micro assemblies" },
  { text: "26103 - Manufacture of electrical capacitors and resistors" },
  { text: "26104 - Manufacture of printed circuit boards" },
  { text: "26105 - Manufacture of display components" },
  { text: "26109 - Manufacture of other components for electronic applications" },
  { text: "26201 - Manufacture of computers" },
  { text: "26202 - Manufacture of peripheral equipment" },
  { text: "26300 - Manufacture of communication equipment" },
  { text: "26400 - Manufacture of consumer electronics" },
  { text: "26511 - Manufacture of measuring, testing, navigating and control equipment" },
  { text: "26512 - Manufacture of industrial process control equipment" },
  { text: "26520 - Manufacture of watches and clocks and parts" },
  { text: "26600 - Manufacture of irradiation, electro medical and electrotherapeutic equipment" },
  { text: "26701 - Manufacture of optical instruments and equipment" },
  { text: "26702 - Manufacture of photographic equipment" },
  { text: "26800 - Manufacture of magnetic and optical recording media" },
  { text: "27101 - Manufacture of electric motors, generators and transformers" },
  { text: "27102 - Manufacture of electricity distribution and control apparatus" },
  { text: "27200 - Manufacture of batteries and accumulators" },
  { text: "27310 - Manufacture of fibre optic cables" },
  { text: "27320 - Manufacture of other electronic and electric wires and cables" },
  { text: "27330 - Manufacture of current-carrying and non current-carrying wiring devices for electrical circuits regardless of material" },
  { text: "27400 - Manufacture of electric lighting equipment" },
  { text: "27500 - Manufacture of domestic appliances" },
  { text: "27900 - Manufacture of miscellaneous electrical equipment other than motors, generators and transformers, batteries and accumulators, wires and wiring devices, lighting equipment or domestic appliances" },
  { text: "28110 - Manufacture of engines and turbines, except aircraft, vehicle and cycle engines" },
  { text: "28120 - Manufacture of fluid power equipment" },
  { text: "28130 - Manufacture of other pumps, compressors, taps and valves" },
  { text: "28140 - Manufacture of bearings, gears, gearing and driving elements" },
  { text: "28150 - Manufacture of ovens, furnaces and furnace burners" },
  { text: "28160 - Manufacture of lifting and handling equipment" },
  { text: "28170 - Manufacture of office machinery and equipment (except computers and peripheral equipment)" },
  { text: "28180 - Manufacture of power-driven hand tools with self-contained electric or non-electric motor or pneumatic drives" },
  { text: "28191 - Manufacture of refrigerating or freezing industrial equipment" },
  { text: "28192 - Manufacture of air-conditioning machines, including for motor vehicles" },
  { text: "28199 - Manufacture of other general-purpose machinery n.e.c." },
  { text: "28210 - Manufacture of agricultural and forestry machinery" },
  { text: "28220 - Manufacture of metal-forming machinery and machine tools" },
  { text: "28230 - Manufacture of machinery for metallurgy" },
  { text: "28240 - Manufacture of machinery for mining, quarrying and construction" },
  { text: "28250 - Manufacture of machinery for food, beverage and tobacco processing" },
  { text: "28260 - Manufacture of machinery for textile, apparel and leather production" },
  { text: "28290 - Manufacture of other special-purpose machinery n.e.c." },
  { text: "29101 - Manufacture of passenger cars" },
  { text: "29102 - Manufacture of commercial vehicles" },
  { text: "29200 - Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semitrailers" },
  { text: "29300 - Manufacture of parts and accessories for motor vehicles" },
  { text: "30110 - Building of ships and floating structures" },
  { text: "30120 - Building of pleasure and sporting boats" },
  { text: "30200 - Manufacture of railway locomotives and rolling stock" },
  { text: "30300 - Manufacture of air and spacecraft and related machinery" },
  { text: "30400 - Manufacture of military fighting vehicles" },
  { text: "30910 - Manufacture of motorcycles" },
  { text: "30920 - Manufacture of bicycles and invalid carriages" },
  { text: "30990 - Manufacture of other transport equipments n.e.c." },
  { text: "31001 - Manufacture of wooden and cane furniture" },
  { text: "31002 - Manufacture of metal furniture" },
  { text: "31003 - Manufacture of mattress" },
  { text: "31009 - Manufacture of other furniture, except of stone, concrete or ceramic" },
  { text: "32110 - Manufacture of jewellery and related articles" },
  { text: "32120 - Manufacture of imitation jewellery and related articles" },
  { text: "32200 - Manufacture of musical instruments" },
  { text: "32300 - Manufacture of sports goods" },
  { text: "32400 - Manufacture of games and toys" },
  { text: "32500 - Manufacture of medical and dental instrument and supplies" },
  { text: "32901 - Manufacture of stationery" },
  { text: "32909 - Other manufacturing n.e.c." },
  { text: "33110 - Repair of fabricated metal products" },
  { text: "33120 - Repair and maintenance of industrial machinery and equipment" },
  { text: "33131 - Repair and maintenance of the measuring, testing, navigating and control equipment" },
  { text: "33132 - Repair and maintenance of irradiation, electro medical and electrotherapeutic equipment" },
  { text: "33133 - Repair of optical instruments and photographic equipment" },
  { text: "33140 - Repair and maintenance of electrical equipment except domestic appliances" },
  { text: "33150 - Repair and maintenance of transport equipment except motorcycles and bicycles" },
  { text: "33190 - Repair and maintenance of other equipment n.e.c." },
  { text: "33200 - Installation of industrial machinery and equipment" },
  { text: "35101 - Operation of generation facilities that produce electric energy" },
  { text: "35102 - Operation of transmission, distribution and sales of electricity" },
  { text: "35201 - Manufacture of gaseous fuels with a specified calorific value, by purification, blending and other processes from gases of various types including natural gas" },
  { text: "35202 - Transportation, distribution and supply of gaseous fuels of all kinds through a system of mains" },
  { text: "35203 - Sale of gas to the user through mains" },
  { text: "35301 - Production, collection and distribution of steam and hot water for heating, power and other purposes" },
  { text: "35302 - Production and distribution of cooled air, chilled water for cooling purposes" },
  { text: "35303 - Production of ice, including ice for food and non-food (e.g. cooling) purposes" },
  { text: "36001 - Purification and distribution of water for water supply purposes" },
  { text: "36002 - Desalting of sea or ground water to produce water as the principal product of interest" },
  { text: "38111 - Collection of non-hazardous solid waste (i.e. garbage) within a local area" },
  { text: "38112 - Collection of recyclable materials" },
  { text: "38113 - Collection of refuse in litter-bins in public places" },
  { text: "38114 - Collection of construction and demolition waste" },
  { text: "38115 - Operation of waste transfer stations for non-hazardous waste" },
  { text: "38121 - Collection of hazardous waste" },
  { text: "38122 - Operation of waste transfer stations for hazardous waste" },
  { text: "38210 - Treatment and disposal of non-hazardous waste" },
  { text: "38220 - Treatment and disposal of hazardous waste" },
  { text: "38301 - Mechanical crushing of metal waste" },
  { text: "38302 - Dismantling of automobiles, computers, televisions and other equipment for material recover" },
  { text: "38303 - Reclaiming of rubber such as used tires to produce secondary raw material" },
  { text: "38304 - Reuse of rubber products" },
  { text: "38309 - Materials recovery n.e.c." },
  { text: "39000 - Remediation activities and other waste management services" },
  { text: "41001 - Residential buildings" },
  { text: "41002 - Non-residential buildings" },
  { text: "41003 - Assembly and erection of prefabricated constructions on the site" },
  { text: "41009 - Construction of buildings n.e.c." },
  { text: "42101 - Construction of motorways, streets, roads, other vehicular and pedestrian ways" },
  { text: "42102 - Surface work on streets, roads, highways, bridges or tunnels" },
  { text: "42103 - Construction of bridges, including those for elevated highways" },
  { text: "42104 - Construction of tunnels" },
  { text: "42105 - Construction of railways and subways" },
  { text: "42106 - Construction of airfield/airports runways" },
  { text: "42109 - Construction of roads and railways n.e.c." },
  { text: "42201 - Long-distance pipelines, communication and power lines" },
  { text: "42202 - Urban pipelines, urban communication and power lines; ancillary urban works" },
  { text: "42203 - Water main and line construction" },
  { text: "42204 - Reservoirs" },
  { text: "42205 - Construction of irrigation systems (canals)" },
  { text: "42206 - Construction of sewer systems (including repair) and sewage disposal plants" },
  { text: "42207 - Construction of power plants" },
  { text: "42209 - Construction of utility projects n.e.c." },
  { text: "42901 - Construction of refineries" },
  { text: "42902 - Construction of waterways, harbour and river works, pleasure ports (marinas), locks" },
  { text: "42903 - Construction of dams and dykes" },
  { text: "42904 - Dredging of waterways" },
  { text: "42905 - Outdoor sports facilities" },
  { text: "42906 - Land subdivision with land improvement" },
  { text: "42909 - Construction of other engineering projects n.e.c." },
  { text: "43110 - Demolition or wrecking of buildings and other structures" },
  { text: "43121 - Clearing of building sites" },
  { text: "43122 - Earth moving" },
  { text: "43123 - Drilling, boring and core sampling for construction, geophysical, geological or similar purposes" },
  { text: "43124 - Site preparation for mining" },
  { text: "43125 - Drainage of agricultural or forestry land" },
  { text: "43126 - Land reclamation work" },
  { text: "43129 - Other site preparation activities n.e.c." },
  { text: "43211 - Electrical wiring and fittings" },
  { text: "43212 - Telecommunications wiring" },
  { text: "43213 - Computer network and cable television wiring" },
  { text: "43214 - Satellite dishes" },
  { text: "43215 - Lighting systems" },
  { text: "43216 - Security systems" },
  { text: "43219 - Electrical installation n.e.c." },
  { text: "43221 - Installation of heating systems (electric, gas and oil)" },
  { text: "43222 - Installation of furnaces, cooling towers" },
  { text: "43223 - Installation of non-electric solar energy collectors" },
  { text: "43224 - Installation of plumbing and sanitary equipment" },
  { text: "43225 - Installation of ventilation, refrigeration or air-conditioning equipment and ducts" },
  { text: "43226 - Installation of gas fittings" },
  { text: "43227 - Installation of fire and lawn sprinkler systems" },
  { text: "43228 - Steam piping" },
  { text: "43229 - Plumbing, heat and air-conditioning installation n.e.c." },
  { text: "43291 - Installation of elevators, escalators in buildings or other construction projects" },
  { text: "43292 - Installation of automated and revolving doors in buildings or other construction projects" },
  { text: "43293 - Installation of lighting conductors in buildings or other construction projects" },
  { text: "43294 - Installation vacuum cleaning systems in buildings or other construction projects" },
  { text: "43295 - Installation thermal, sound or vibration insulation in buildings or other construction projects" },
  { text: "43299 - Other construction installation n.e.c." },
  { text: "43301 - Installation of doors, windows, door and window frames of wood or other materials, fitted kitchens, staircases, shop fittings and furniture" },
  { text: "43302 - Laying, tiling, hanging or fitting in buildings or other construction projects of various types of materials" },
  { text: "43303 - Interior and exterior painting of buildings" },
  { text: "43304 - Painting of civil engineering structures" },
  { text: "43305 - Installation of glass, mirrors" },
  { text: "43306 - Interior completion" },
  { text: "43307 - Cleaning of new buildings after construction" },
  { text: "43309 - Other building completion and finishing work n.e.c." },
  { text: "43901 - Construction of foundations, including pile driving" },
  { text: "43902 - Erection of non-self-manufactured steel elements" },
  { text: "43903 - Scaffolds and work platform erecting and dismantling" },
  { text: "43904 - Bricklaying and stone setting" },
  { text: "43905 - Construction of outdoor swimming pools" },
  { text: "43906 - Steam cleaning, sand blasting and similar activities for building exteriors" },
  { text: "43907 - Renting of construction machinery and equipment with operator (e.g. cranes)" },
  { text: "43909 - Other specialized construction activities, n.e.c." },
  { text: "45101 - Wholesale and retail of new motor vehicles" },
  { text: "45102 - Wholesale and retail of used motor vehicles" },
  { text: "45103 - Sale of industrial, commercial and agriculture vehicles - new" },
  { text: "45104 - Sale of industrial, commercial and agriculture vehicles - used" },
  { text: "45105 - Sale by commission agents" },
  { text: "45106 - Car auctions" },
  { text: "45109 - Sale of other motor vehicles n.e.c." },
  { text: "45201 - Maintenance and repair of motor vehicles" },
  { text: "45202 - Spraying and painting" },
  { text: "45203 - Washing and polishing (car wash)" },
  { text: "45204 - Repair of motor vehicle seats" },
  { text: "45205 - Installation of parts and accessories not as part of the manufacturing process" },
  { text: "45300 - Wholesale and retail sale of all kinds of parts, components, supplies, tools and accessories for motor vehicles" },
  { text: "45401 - Wholesale and retail sale of motorcycles" },
  { text: "45402 - Wholesale and retail sale of parts and accessories for motorcycles" },
  { text: "45403 - Repair and maintenance of motorcycles" },
  { text: "46100 - Wholesale on a fee or contract basis" },
  { text: "46201 - Wholesale of rubber" },
  { text: "46202 - Wholesale of palm oil" },
  { text: "46203 - Wholesale of lumber and timber" },
  { text: "46204 - Wholesale of flowers and plants" },
  { text: "46205 - Wholesale of livestock" },
  { text: "46209 - Wholesale of agricultural raw material and live animal n.e.c." },
  { text: "46311 - Wholesale of meat, poultry and eggs" },
  { text: "46312 - Wholesale of fish and other seafood" },
  { text: "46313 - Wholesale of fruits" },
  { text: "46314 - Wholesale of vegetables" },
  { text: "46319 - Wholesale of meat, fish, fruits and vegetables n.e.c." },
  { text: "46321 - Wholesale of rice, other grains, flour and sugars" },
  { text: "46322 - Wholesale of dairy products" },
  { text: "46323 - Wholesale of confectionary" },
  { text: "46324 - Wholesale of biscuits, cakes, breads and other bakery products" },
  { text: "46325 - Wholesale of coffee, tea, cocoa and other beverages" },
  { text: "46326 - Wholesale of beer, wine and spirits" },
  { text: "46327 - Wholesale of tobacco, cigar, cigarettes" },
  { text: "46329 - Wholesale of other foodstuffs" },
  { text: "46411 - Wholesale of yarn and fabrics" },
  { text: "46412 - Wholesale of household linen, towels, blankets" },
  { text: "46413 - Wholesale of clothing" },
  { text: "46414 - Wholesale of clothing accessories" },
  { text: "46415 - Wholesale of fur articles" },
  { text: "46416 - Wholesale of footwear" },
  { text: "46417 - Wholesale of haberdashery" },
  { text: "46419 - Wholesale of textiles, clothing n.e.c." },
  { text: "46421 - Wholesale of pharmaceutical and medical goods" },
  { text: "46422 - Wholesale of perfumeries, cosmetics, soap and toiletries" },
  { text: "46431 - Wholesale of bicycles and their parts and accessories" },
  { text: "46432 - Wholesale of photographic and optical goods" },
  { text: "46433 - Wholesale of leather goods and travel accessories" },
  { text: "46434 - Wholesale of musical instruments, games and toys, sports goods" },
  { text: "46441 - Wholesale of handicrafts and artificial flowers" },
  { text: "46442 - Wholesale of cut flowers and plants" },
  { text: "46443 - Wholesale of watches and clocks" },
  { text: "46444 - Wholesale of jewellery" },
  { text: "46491 - Wholesale of household furniture" },
  { text: "46492 - Wholesale of household appliances" },
  { text: "46493 - Wholesale of lighting equipment" },
  { text: "46494 - Wholesale of household utensils and cutlery, crockery, glassware, chinaware and pottery" },
  { text: "46495 - Wholesale of woodenware, wickerwork and corkware" },
  { text: "46496 - Wholesale of electrical and electronic goods" },
  { text: "46497 - Wholesale of stationery, books, magazines and newspapers" },
  { text: "46499 - Wholesale of other household goods n.e.c." },
  { text: "46510 - Wholesale of computer hardware, software and peripherals" },
  { text: "46521 - Wholesale of telephone and telecommunications equipment, cell phones, pagers" },
  { text: "46522 - Wholesale of electronic components and wiring accessories" },
  { text: "46531 - Wholesale of agricultural machinery, equipment and supplies" },
  { text: "46532 - Wholesale of lawn mowers however operated" },
  { text: "46591 - Wholesale of office machinery and business equipment, except computers and computer peripheral equipment" },
  { text: "46592 - Wholesale of office furniture" },
  { text: "46593 - Wholesale of computer-controlled machines tools" },
  { text: "46594 - Wholesale of industrial machinery, equipment and supplies" },
  { text: "46595 - Wholesale of construction and civil engineering machinery and equipment" },
  { text: "46596 - Wholesale of lift escalators, air-conditioning, security and fire fighting equipment" },
  { text: "46599 - Wholesale of other machinery for use in industry, trade and navigation and other services n.e.c." },
  { text: "46611 - Wholesale of petrol, diesel, lubricants" },
  { text: "46612 - Wholesale of liquefied petroleum gas" },
  { text: "46619 - Wholesale of other solid, liquid and gaseous fuels and related products n.e.c." },
  { text: "46621 - Wholesale of ferrous and non-ferrous metal ores and metals" },
  { text: "46622 - Wholesale of ferrous and non-ferrous semi-finished metal ores and products n.e.c." },
  { text: "46631 - Wholesale of logs, sawn timber, plywood, veneer and related products" },
  { text: "46632 - Wholesale of paints and varnish" },
  { text: "46633 - Wholesale of construction materials" },
  { text: "46634 - Wholesale of fittings and fixtures" },
  { text: "46635 - Wholesale of hot water heaters" },
  { text: "46636 - Wholesale of sanitary installation and equipment" },
  { text: "46637 - Wholesale of tools" },
  { text: "46639 - Wholesale of other construction materials, hardware, plumbing and heating equipment and supplies n.e.c." },
  { text: "46691 - Wholesale of industrial chemicals" },
  { text: "46692 - Wholesale of fertilizers and agrochemical products" },
  { text: "46693 - Wholesale of plastic materials in primary forms" },
  { text: "46694 - Wholesale of rubber scrap" },
  { text: "46695 - Wholesale of textile fibres" },
  { text: "46696 - Wholesale of paper in bulk, packaging materials" },
  { text: "46697 - Wholesale of precious stones" },
  { text: "46698 - Wholesale of metal and non-metal waste and scrap and materials for recycling" },
  { text: "46699 - Dismantling of automobiles, computer, televisions and other equipment to obtain and re-sell usable parts" },
  { text: "46901 - Wholesale of aquarium fishes, pet birds and animals" },
  { text: "46902 - Wholesale of animal/pet food" },
  { text: "46909 - Wholesale of a variety of goods without any particular specialization n.e.c." },
  { text: "47111 - Provision stores" },
  { text: "47112 - Supermarket" },
  { text: "47113 - Mini market" },
  { text: "47114 - Convenience stores" },
  { text: "47191 - Department stores" },
  { text: "47192 - Department stores and supermarket" },
  { text: "47193 - Hypermarket" },
  { text: "47194 - News agent and miscellaneous goods store" },
  { text: "47199 - Other retail sale in non-specialized stores n.e.c." },
  { text: "47211 - Retail sale of rice, flour, other grains and sugars" },
  { text: "47212 - Retail sale of fresh or preserved vegetables and fruits" },
  { text: "47213 - Retail sale of dairy products and eggs" },
  { text: "47214 - Retail sale of meat and meat products (including poultry)" },
  { text: "47215 - Retail sale of fish, other seafood and products thereof" },
  { text: "47216 - Retail sale of bakery products and sugar confectionery" },
  { text: "47217 - Retail sale of mee, kuey teow, mee hoon, wantan skins and other food products made from flour or soya" },
  { text: "47219 - Retail sale of other food products n.e.c." },
  { text: "47221 - Retail sale of beer, wine and spirits" },
  { text: "47222 - Retail sale of tea, coffee, soft drinks, mineral water and other beverages" },
  { text: "47230 - Retail sale of tobacco products in specialized store" },
  { text: "47300 - Retail sale of automotive fuel in specialized stores" },
  { text: "47411 - Retail sale of computers, computer equipment and supplies" },
  { text: "47412 - Retail sale of video game consoles and non-customized software" },
  { text: "47413 - Retail sale of telecommunication equipment" },
  { text: "47420 - Retail sale of audio and video equipment in specialized store" },
  { text: "47510 - Retail sale of textiles in specialized stores" },
  { text: "47520 - Retail sale of construction materials, hardware, paints and glass" },
  { text: "47531 - Retail sale of carpets and rugs" },
  { text: "47532 - Retail sale of curtains and net curtains" },
  { text: "47533 - Retail sale of wallpaper and floor coverings" },
  { text: "47591 - Retail sale of household furniture" },
  { text: "47592 - Retail sale of articles for lighting" },
  { text: "47593 - Retail sale of household utensils and cutlery, crockery, glassware, chinaware and pottery" },
  { text: "47594 - Retail sale of wood, cork goods and wickerwork goods" },
  { text: "47595 - Retail sale of household appliances" },
  { text: "47596 - Retail sale of musical instruments and scores" },
  { text: "47597 - Retail sale of security systems" },
  { text: "47598 - Retail sale of household articles and equipment n.e.c." },
  { text: "47611 - Retail sale of office supplies and equipment" },
  { text: "47612 - Retail sale of books, newspapers and stationary" },
  { text: "47620 - Retail sale of musical records, audio tapes, compact discs , cassettes, video tapes, VCDs and DVDs, blank tapes and discs" },
  { text: "47631 - Retail sale of sports goods and equipments" },
  { text: "47632 - Retail sale of fishing equipment" },
  { text: "47633 - Retail sale of camping goods" },
  { text: "47634 - Retail sale of boats and equipments" },
  { text: "47635 - Retail sale of bicycles and related parts and accessories" },
  { text: "47640 - Retail sale of games and toys, made of all materials" },
  { text: "47711 - Retail sale of articles of clothing, articles of fur and clothing accessories" },
  { text: "47712 - Retail sale of footwear" },
  { text: "47713 - Retail sale of leather goods, accessories of leather and leather substitutes" },
  { text: "47721 - Stores specialized in retail sale of pharmaceuticals, medical and orthopaedic goods" },
  { text: "47722 - Stores specialized in retail sale of perfumery, cosmetic and toilet articles" },
  { text: "47731 - Retail sale of photographic and precision equipment" },
  { text: "47732 - Retail sale of watches and clocks" },
  { text: "47733 - Retail sale of jewellery" },
  { text: "47734 - Retail sale of flowers, plants, seeds, fertilizers" },
  { text: "47735 - Retail sale of souvenirs, craftwork and religious articles" },
  { text: "47736 - Retail sale of household fuel oil, cooking gas, coal and fuel wood" },
  { text: "47737 - Retail sale of spectacles and other optical goods" },
  { text: "47738 - Retail sale of aquarium fishes, pet animals and pet food" },
  { text: "47739 - Other retail sale of new goods in specialized stores n.e.c." },
  { text: "47741 - Retail sale of second-hand books" },
  { text: "47742 - Retail sale of second-hand electrical and electronic goods" },
  { text: "47743 - Retail sale of antiques" },
  { text: "47744 - Activities of auctioning houses (retail)" },
  { text: "47749 - Retail sale of second-hand goods n.e.c." },
  { text: "47810 - Retail sale of food, beverages and tobacco products via stalls or markets" },
  { text: "47820 - Retail sale of textiles, clothing and footwear via stalls or markets" },
  { text: "47891 - Retail sale of carpets and rugs via stalls or markets" },
  { text: "47892 - Retail sale of books via stalls or markets" },
  { text: "47893 - Retail sale of games and toys via stalls or markets" },
  { text: "47894 - Retail sale of household appliances and consumer electronics via stall or markets" },
  { text: "47895 - Retail sale of music and video recordings via stall or markets" },
  { text: "47911 - Retail sale of any kind of product by mail order" },
  { text: "47912 - Retail sale of any kind of product over the Internet" },
  { text: "47913 - Direct sale via television, radio and telephone" },
  { text: "47914 - Internet retail auctions" },
  { text: "47991 - Retail sale of any kind of product by direct sales or door-to-door sales persons" },
  { text: "47992 - Retail sale of any kind of product through vending machines" },
  { text: "47999 - Other retail sale not in stores, stalls or markets n.e.c." },
  { text: "49110 - Passenger transport by inter-urban railways" },
  { text: "49120 - Freight transport by inter-urban, suburban and urban railways" },
  { text: "49211 - City bus services" },
  { text: "49212 - Urban and suburban railway passenger transport service" },
  { text: "49221 - Express bus services" },
  { text: "49222 - Employees bus services" },
  { text: "49223 - School bus services" },
  { text: "49224 - Taxi operation and limousine services" },
  { text: "49225 - Rental of cars with driver" },
  { text: "49229 - Other passenger land transport n.e.c." },
  { text: "49230 - Freight transport by road" },
  { text: "49300 - Transport via pipeline" },
  { text: "50111 - Operation of excursion, cruise or sightseeing boats" },
  { text: "50112 - Operation of ferries, water taxis" },
  { text: "50113 - Rental of pleasure boats with crew for sea and coastal water transport" },
  { text: "50121 - Transport of freight overseas and coastal waters, whether scheduled or not" },
  { text: "50122 - Transport by towing or pushing of barges, oil rigs" },
  { text: "50211 - Transport of passenger via rivers, canals, lakes and other inland waterways" },
  { text: "50212 - Rental of pleasure boats with crew for inland water transport" },
  { text: "50220 - Transport of freight via rivers, canals, lakes and other inland waterways" },
  { text: "51101 - Transport of passengers by air over regular routes and on regular schedules" },
  { text: "51102 - Non-scheduled transport of passenger by air" },
  { text: "51103 - Renting of air-transport equipment with operator for the purpose of passenger transportation" },
  { text: "51201 - Transport freight by air over regular routes and on regular schedules" },
  { text: "51202 - Non-scheduled transport of freight by air" },
  { text: "51203 - Renting of air-transport equipment with operator for the purpose of freight transportation" },
  { text: "52100 - Warehousing and storage services" },
  { text: "52211 - Operation of terminal facilities" },
  { text: "52212 - Towing and road side assistance" },
  { text: "52213 - Operation of parking facilities for motor vehicles (parking lots)" },
  { text: "52214 - Highway, bridge and tunnel operation services" },
  { text: "52219 - Other service activities incidental to land transportation n.e.c." },
  { text: "52221 - Port, harbours and piers operation services" },
  { text: "52222 - Vessel salvage and refloating services" },
  { text: "52229 - Other service activities incidental to water transportation n.e.c." },
  { text: "52231 - Operation of terminal facilities" },
  { text: "52232 - Airport and air-traffic-control activities" },
  { text: "52233 - Ground service activities on airfields" },
  { text: "52234 - Fire fighting and fire-prevention services at airports" },
  { text: "52239 - Other service activities incidental to air transportation n.e.c." },
  { text: "52241 - Stevedoring services" },
  { text: "52249 - Other cargo handling activities n.e.c." },
  { text: "52291 - Forwarding of freight" },
  { text: "52292 - Brokerage for ship and aircraft space" },
  { text: "52299 - Other transportation support activities n.e.c." },
  { text: "53100 - National postal services" },
  { text: "53200 - Courier activities other than national post activities" },
  { text: "55101 - Hotels and resort hotels" },
  { text: "55102 - Motels" },
  { text: "55103 - Apartment hotels" },
  { text: "55104 - Chalets" },
  { text: "55105 - Rest house/guest house" },
  { text: "55106 - Bed and breakfast units" },
  { text: "55107 - Hostels" },
  { text: "55108 - Home stay" },
  { text: "55109 - Other short term accommodation activities n.e.c." },
  { text: "55200 - Camping grounds, recreational vehicle parks and trailer parks" },
  { text: "55900 - Other accommodation" },
  { text: "56101 - Restaurants and restaurant cum night clubs" },
  { text: "56102 - Cafeterias/canteens" },
  { text: "56103 - Fast-food restaurants" },
  { text: "56104 - Ice cream truck vendors and parlours" },
  { text: "56105 - Mobile food carts" },
  { text: "56106 - Food stalls/hawkers" },
  { text: "56107 - Food or beverage, food and beverage preparation in market stalls/hawkers" },
  { text: "56210 - Event/food caterers" },
  { text: "56290 - Other food service activities" },
  { text: "56301 - Pubs, bars, discotheques, coffee houses, cocktail lounges and karaoke" },
  { text: "56302 - Coffee shops" },
  { text: "56303 - Drink stalls/hawkers" },
  { text: "56304 - Mobile beverage" },
  { text: "56309 - Others drinking places n.e.c." },
  { text: "58110 - Publishing of books, brochures and other publications" },
  { text: "58120 - Publishing of mailing lists, telephone book, other directories" },
  { text: "58130 - Publishing of newspapers, journals, magazines and periodicals in print or electronic form" },
  { text: "58190 - Publishing of catalogues, photos, engraving and postcards, greeting cards, forms, posters, reproduction of works of art, advertising material and other printed matter n.e.c." },
  { text: "58201 - Business and other applications" },
  { text: "58202 - Computer games for all platforms" },
  { text: "58203 - Operating systems" },
  { text: "59110 - Motion picture, video and television programme production activities" },
  { text: "59120 - Motion picture, video and television programme post-production activities" },
  { text: "59130 - Motion picture, video and television programme distribution activities" },
  { text: "59140 - Motion picture projection activities" },
  { text: "59200 - Sound recording and music publishing activities" },
  { text: "60100 - Radio broadcasting" },
  { text: "60200 - Television programming and broadcasting activities" },
  { text: "61101 - Wired telecommunications services" },
  { text: "61102 - Internet access providers by the operator of the wired infrastructure" },
  { text: "61201 - Wireless telecommunications services" },
  { text: "61202 - Internet access providers by the operator of the wireless infrastructure" },
  { text: "61300 - Satellite telecommunications services" },
  { text: "61901 - Provision of Internet access over networks between the client and the ISP not owned or controlled by the ISP" },
  { text: "61902 - Provision of telecommunications services over existing telecom connection" },
  { text: "61903 - Telecommunications resellers" },
  { text: "61904 - Provision of telecommunications services over existing telecom connections VOIP (Voice Over Internet Protocol) provision" },
  { text: "61905 - Provision of specialized telecommunications applications" },
  { text: "61909 - Other telecommunications activities n.e.c." },
  { text: "62010 - Computer programming activities" },
  { text: "62021 - Computer consultancy" },
  { text: "62022 - Computer facilities management activities" },
  { text: "62091 - Information Communication Technology (ICT) system security" },
  { text: "62099 - Other information technology service activities n.e.c." },
  { text: "63111 - Activities of providing infrastructure for hosting, data processing services and related activities" },
  { text: "63112 - Data processing activities" },
  { text: "63120 - Web portals" },
  { text: "63910 - News syndicate and news agency activities" },
  { text: "63990 - Other information service activities n.e.c." },
  { text: "64110 - Central banking" },
  { text: "64191 - Commercial Banks" },
  { text: "64192 - Islamic Banks" },
  { text: "64193 - Offshore Banks" },
  { text: "64194 - Investment Banks" },
  { text: "64195 - Development financial institutions (with deposit taking functions)" },
  { text: "64199 - Other monetary intermediation (with deposit taking functions) n.e.c." },
  { text: "64200 - Activities of holding companies" },
  { text: "64301 - Venture capital companies" },
  { text: "64302 - Unit trust fund excludes REITs" },
  { text: "64303 - Property unit trust (REITs)" },
  { text: "64304 - Other administration of trusts accounts" },
  { text: "64309 - Trusts, funds and similar financial entities n.e.c." },
  { text: "64910 - Financial leasing activities" },
  { text: "64921 - Development financial institutions (without deposit taking functions)" },
  { text: "64922 - Credit card services" },
  { text: "64923 - Licensed money lending activities" },
  { text: "64924 - Pawnshops and pawnbrokers includes Ar-Rahnu" },
  { text: "64925 - Co-operative with credits functions" },
  { text: "64929 - Other credit granting n.e.c." },
  { text: "64991 - Factoring companies" },
  { text: "64992 - Representative office of foreign banks" },
  { text: "64993 - Nominee companies" },
  { text: "64999 - Other financial service activities, except insurance/takaful and pension funding n.e.c." },
  { text: "65111 - Life insurance" },
  { text: "65112 - Family takaful" },
  { text: "65121 - General insurance" },
  { text: "65122 - General takaful" },
  { text: "65123 - Composite insurance" },
  { text: "65124 - Offshore insurance" },
  { text: "65125 - Offshore takaful" },
  { text: "65201 - Life reinsurance" },
  { text: "65202 - Family retakaful" },
  { text: "65203 - General reinsurance" },
  { text: "65204 - General retakaful" },
  { text: "65205 - Composite retakaful" },
  { text: "65206 - Offshore reinsurance" },
  { text: "65207 - Offshore retakaful" },
  { text: "65301 - Pension funding" },
  { text: "65302 - Provident funding" },
  { text: "66111 - Stock exchanges" },
  { text: "66112 - Exchanges for commodity contracts" },
  { text: "66113 - Securities exchange" },
  { text: "66114 - Exchanges for commodity futures contracts" },
  { text: "66119 - Administration of financial markets n.e.c." },
  { text: "66121 - Stock, share and bond brokers" },
  { text: "66122 - Commodity brokers and dealers" },
  { text: "66123 - Gold bullion dealers" },
  { text: "66124 - Foreign exchange broker and dealers (Bureaux de change)" },
  { text: "66125 - Money-changing services" },
  { text: "66129 - Other financial and commodity futures brokers and dealers" },
  { text: "66191 - Investment advisory services" },
  { text: "66192 - Financial consultancy services" },
  { text: "66199 - Activities auxiliary to finance n.e.c." },
  { text: "66211 - Insurance adjusting service" },
  { text: "66212 - Takaful adjusting service" },
  { text: "66221 - Insurance agents" },
  { text: "66222 - Takaful agents" },
  { text: "66223 - Insurance brokers" },
  { text: "66224 - Takaful brokers" },
  { text: "66290 - Other activities auxiliary to insurance, takaful and pension funding" },
  { text: "66301 - Management of pension funds" },
  { text: "66302 - Assets/portfolio management" },
  { text: "66303 - Unit trust management companies" },
  { text: "68101 - Buying, selling, renting and operating of self-owned or leased real estate - residential buildings" },
  { text: "68102 - Buying, selling, renting and operating of self-owned or leased real estate - non-residential buildings" },
  { text: "68103 - Buying, selling, renting and operating of self-owned or leased real estate - land" },
  { text: "68104 - Development of building projects for own operation, i.e. for renting of space in these buildings" },
  { text: "68109 - Real estate activities with own or leased property n.e.c." },
  { text: "68201 - Activities of real estate agents and brokers for buying, selling and renting of real estate" },
  { text: "68202 - Management of real estate on a fee or contract basis" },
  { text: "68203 - Appraisal services for real estate" },
  { text: "68209 - Real estate activities on a fee or contract basis n.e.c." },
  { text: "69100 - Legal activities" },
  { text: "69200 - Accounting, bookkeeping and auditing activities; tax consultancy" },
  { text: "70100 - Activities of head offices" },
  { text: "70201 - Business management consultancy services" },
  { text: "70202 - Human resource consultancy services" },
  { text: "70203 - Consultancy services in public relation and communications" },
  { text: "70209 - Other management consultancy activities n.e.c" },
  { text: "71101 - Architectural services" },
  { text: "71102 - Engineering services" },
  { text: "71103 - Land surveying services" },
  { text: "71109 - Other architectural and engineering activities and related technical consultancy n.e.c." },
  { text: "71200 - Technical testing and analysis" },
  { text: "72101 - Research and development on natural sciences" },
  { text: "72102 - Research and development on engineering and technology" },
  { text: "72103 - Research and development on medical sciences" },
  { text: "72104 - Research and development on biotechnology" },
  { text: "72105 - Research and development on agricultural sciences" },
  { text: "72106 - Research and development on Information Communication Technology (ICT)" },
  { text: "72109 - Research and development on other natural science and engineering n.e.c." },
  { text: "72201 - Research and development on social sciences" },
  { text: "72202 - Research and development on humanities" },
  { text: "72209 - Research and development of other social sciences and humanities n.e.c." },
  { text: "73100 - Advertising" },
  { text: "73200 - Market research and public opinion polling" },
  { text: "74101 - Activities of interior decorators" },
  { text: "74102 - Services of graphic designers" },
  { text: "74103 - Fashion design services" },
  { text: "74109 - Specialized design activities n.e.c." },
  { text: "74200 - Photographic activities" },
  { text: "74901 - Translation and interpretation activities" },
  { text: "74902 - Business brokerage activities" },
  { text: "74903 - Security consulting" },
  { text: "74904 - Activities of quantity surveyors" },
  { text: "74905 - Activities of consultants other than architecture, engineering and management consultants" },
  { text: "74909 - Any other professional, scientific and technical activities n.e.c." },
  { text: "75000 - VETERINARY ACTIVITIES" },
  { text: "77101 - Renting and operational leasing of passenger cars (without driver)" },
  { text: "77102 - Renting and operational leasing of trucks, utility trailers and recreational vehicles" },
  { text: "77211 - Renting and leasing of pleasure boats, canoes, sailboats" },
  { text: "77212 - Renting and leasing of bicycles" },
  { text: "77213 - Renting and leasing of beach chairs and umbrellas" },
  { text: "77219 - Renting and leasing of other sports equipment n.e.c." },
  { text: "77220 - Renting of video tapes, records, CDs, DVDs" },
  { text: "77291 - Renting and leasing of textiles, wearing apparel and footwear" },
  { text: "77292 - Renting and leasing of furniture, pottery and glass, kitchen and tableware, electrical appliances and house wares" },
  { text: "77293 - Renting and leasing of jewellery, musical instruments, scenery and costumes" },
  { text: "77294 - Renting and leasing of books, journals and magazines" },
  { text: "77295 - Renting and leasing of machinery and equipment used by amateurs or as a hobby" },
  { text: "77296 - Renting of flowers and plants" },
  { text: "77297 - Renting and leasing of electronic equipment for household use" },
  { text: "77299 - Renting and leasing of other personal and household goods n.e.c." },
  { text: "77301 - Renting and operational leasing, without operator, of other machinery and equipment that are generally used as capital goods by industries" },
  { text: "77302 - Renting and operational leasing of land-transport equipment (other than motor vehicles) without drivers" },
  { text: "77303 - Renting and operational leasing of water-transport equipment without operator" },
  { text: "77304 - Renting and operational leasing of air transport equipment without operator" },
  { text: "77305 - Renting and operational leasing of agricultural and forestry machinery and equipment without operator" },
  { text: "77306 - Renting and operational leasing of construction and civil-engineering machinery and equipment without operator" },
  { text: "77307 - Rental and operational leasing of office machinery and equipment without operator" },
  { text: "77309 - Renting and leasing of other machinery, equipment and tangible goods n.e.c." },
  { text: "77400 - Leasing of intellectual property and similar products, except copyrighted works" },
  { text: "78100 - Activities of employment placement agencies" },
  { text: "78200 - Temporary employment agency activities" },
  { text: "78300 - Provision of human resources for client businesses" },
  { text: "79110 - Travel agency activities" },
  { text: "79120 - Tour operator activities" },
  { text: "79900 - Other reservation service and related activities" },
  { text: "80100 - Private security activities" },
  { text: "80200 - Security systems service activities" },
  { text: "80300 - Investigation and detective activities" },
  { text: "81100 - Combined facilities support activities" },
  { text: "81210 - General cleaning of buildings" },
  { text: "81291 - Cleaning of buildings of all types" },
  { text: "81292 - Swimming pool cleaning and maintenance services" },
  { text: "81293 - Cleaning of industrial machinery" },
  { text: "81294 - Cleaning of trains, buses, planes" },
  { text: "81295 - Cleaning of pest control services not in connection with agriculture" },
  { text: "81296 - Disinfecting and exterminating activities" },
  { text: "81297 - Cleaning of sea tankers" },
  { text: "81299 - Other building and industrial cleaning activities, n.e.c." },
  { text: "81300 - Landscape care and maintenance service activities" },
  { text: "82110 - Combined office administrative service activities" },
  { text: "82191 - Document preparation, editing and/or proofreading" },
  { text: "82192 - Typing, word processing or desktop publishing" },
  { text: "82193 - Secretarial support services" },
  { text: "82194 - Transcription of documents and other secretarial services" },
  { text: "82195 - Provision of mailbox rental and other postal and mailing services" },
  { text: "82196 - Photocopying, duplicating, blueprinting" },
  { text: "82199 - Photocopying, document preparation and other specialized office support activities n.e.c." },
  { text: "82200 - Activities of call centres" },
  { text: "82301 - Organization, promotions and/or management of event" },
  { text: "82302 - Meeting, incentive, convention, exhibition (MICE)" },
  { text: "82910 - Activities of collection agencies and credit bureaus" },
  { text: "82920 - Packaging activities on a fee or contract basis, whether or not these involve an automated process" },
  { text: "82990 - Other business support service activities n.e.c." },
  { text: "84111 - General (overall) public administration activities" },
  { text: "84112 - Ancillary service activities for the government as a whole" },
  { text: "84121 - Administrative educational services" },
  { text: "84122 - Administrative health care services" },
  { text: "84123 - Administrative housing and local government services" },
  { text: "84124 - Administrative recreational, cultural, arts and sports services" },
  { text: "84125 - Administrative religious affairs services" },
  { text: "84126 - Administrative welfare services" },
  { text: "84129 - Other community and social affairs services" },
  { text: "84131 - Domestic and international trade affairs" },
  { text: "84132 - Agriculture and rural development affairs" },
  { text: "84133 - Primary industries affairs" },
  { text: "84134 - Public works affairs" },
  { text: "84135 - Transport affairs" },
  { text: "84136 - Energy, telecommunication and postal affairs" },
  { text: "84137 - Tourism affairs" },
  { text: "84138 - Human resource affairs" },
  { text: "84139 - Other regulation of and contribution to more efficient operation of businesses n.e.c." },
  { text: "84210 - Foreign affairs" },
  { text: "84220 - Military and civil defence services" },
  { text: "84231 - Police service" },
  { text: "84232 - Prison service" },
  { text: "84233 - Immigration service" },
  { text: "84234 - National registration service" },
  { text: "84235 - Judiciary and legal service" },
  { text: "84236 - Firefighting and fire prevention" },
  { text: "84239 - Other public order and safety affairs related services" },
  { text: "84300 - Compulsory social security activities e.g. SOCSO" },
  { text: "85101 - Pre-primary education (Public)" },
  { text: "85102 - Pre-primary education (Private)" },
  { text: "85103 - Primary education (Public)" },
  { text: "85104 - Primary education (Private)" },
  { text: "85211 - General school secondary education (Public)" },
  { text: "85212 - General school secondary education (Private)" },
  { text: "85221 - Technical and vocational education below the level of higher education (Public)" },
  { text: "85222 - Technical and vocational education below the level of higher education (Private)" },
  { text: "85301 - College and university education (Public)" },
  { text: "85302 - College and university education (Private)" },
  { text: "85411 - Sports instruction" },
  { text: "85412 - Martial arts instruction" },
  { text: "85419 - Any other sports and recreation education n.e.c" },
  { text: "85421 - Music and dancing school" },
  { text: "85429 - Any other cultural education n.e.c." },
  { text: "85491 - Tuition centre" },
  { text: "85492 - Driving school" },
  { text: "85493 - Religious instruction" },
  { text: "85494 - Computer training" },
  { text: "85499 - Others education n.e.c" },
  { text: "85500 - Educational support services for provision of non-instructional services" },
  { text: "86101 - Hospital activities" },
  { text: "86102 - Maternity home services (outside hospital)" },
  { text: "86201 - General medical services" },
  { text: "86202 - Specialized medical services" },
  { text: "86203 - Dental services" },
  { text: "86901 - Dialysis Centres" },
  { text: "86902 - Medical laboratories" },
  { text: "86903 - Physiotherapy and occupational therapy service" },
  { text: "86904 - Acupuncture services" },
  { text: "86905 - Herbalist and homeopathy services" },
  { text: "86906 - Ambulance services" },
  { text: "86909 - Other human health services n.e.c." },
  { text: "87101 - Homes for the elderly with nursing care" },
  { text: "87102 - Nursing homes" },
  { text: "87103 - Palliative or hospices" },
  { text: "87201 - Drug rehabilitation centres" },
  { text: "87209 - Other residential care activities for mental retardation n.e.c." },
  { text: "87300 - Residential care activities for the elderly and disabled" },
  { text: "87901 - Orphanages" },
  { text: "87902 - Welfare homes services" },
  { text: "87909 - Other residential care activities n.e.c." },
  { text: "88101 - Day-care activities for the elderly or for handicapped adults" },
  { text: "88109 - Others social work activities without accommodation for the elderly and disabled" },
  { text: "88901 - Counselling service" },
  { text: "88902 - Child day-care activities" },
  { text: "88909 - Other social work activities without accommodation n.e.c." },
  { text: "90001 - Theatrical producer, singer group band and orchestra entertainment services" },
  { text: "90002 - Operation of concert and theatre halls and other arts facilities" },
  { text: "90003 - Activities of sculptors, painters, cartoonists, engravers, etchers" },
  { text: "90004 - Activities of individual writers, for all subjects" },
  { text: "90005 - Activities of independent journalists" },
  { text: "90006 - Restoring of works of art such as painting" },
  { text: "90007 - Activities of producers or entrepreneurs of arts live events, with or without facilities" },
  { text: "90009 - Creative, arts and entertainment activities n.e.c." },
  { text: "91011 - Documentation and information activities of libraries of all kinds" },
  { text: "91012 - Stock photo libraries and services" },
  { text: "91021 - Operation of museums of all kinds" },
  { text: "91022 - Operation of historical sites and buildings" },
  { text: "91031 - Operation of botanical and zoological gardens" },
  { text: "91032 - Operation of nature reserves, including wildlife preservation" },
  { text: "92000 - GAMBLING AND BETTING ACTIVITIES" },
  { text: "93111 - Football, hockey, cricket, baseball, badminton, futsal, paintball" },
  { text: "93112 - Racetracks for auto" },
  { text: "93113 - Equestrian clubs" },
  { text: "93114 - Swimming pools and stadiums, ice-skating arenas" },
  { text: "93115 - Track and field stadium" },
  { text: "93116 - Golf courses" },
  { text: "93117 - Bowling centre" },
  { text: "93118 - Fitness centres" },
  { text: "93119 - Organization and operation of outdoor or indoor sports events for professionals or amateurs by organizations with own facilities" },
  { text: "93120 - The operation of sports clubs such as football club, bowling club, swimming club" },
  { text: "93191 - Activities of producers or promoters of sports events, with or without facilities" },
  { text: "93192 - Activities of sports leagues and regulating bodies" },
  { text: "93193 - Activities of related to promotion of sporting events" },
  { text: "93199 - Other sports activities n.e.c." },
  { text: "93210 - Activities of amusement parks and theme parks" },
  { text: "93291 - Activities of recreation parks and beaches" },
  { text: "93292 - Operation of recreational transport facilities" },
  { text: "93293 - Renting of leisure and pleasure equipment as an integral part of recreational facilities" },
  { text: "93294 - Operation of fairs and shows of a recreational nature" },
  { text: "93295 - Operation of discotheques and dance floors" },
  { text: "93296 - Activities of producers or entrepreneurs of live events other than arts or sports events, with or without facilities" },
  { text: "93297 - Cyber Cafe/lnternet Centre" },
  { text: "93299 - Any other amusement and recreation activities n.e.c." },
  { text: "94110 - Activities of business and employers membership organizations" },
  { text: "94120 - Activities of professional membership organizations" },
  { text: "94200 - Activities of trade unions" },
  { text: "94910 - Activities of religious organizations" },
  { text: "94920 - Activities of political organizations" },
  { text: "94990 - Activities of other membership organizations n.e.c." },
  { text: "95111 - Repair of electronic equipment" },
  { text: "95112 - Repair and maintenance of computer terminals" },
  { text: "95113 - Repair and maintenance of hand-held computers (PDA's)" },
  { text: "95121 - Repair and maintenance of cordless telephones" },
  { text: "95122 - Repair and maintenance of cellular phones" },
  { text: "95123 - Repair and maintenance of carrier equipment modems" },
  { text: "95124 - Repair and maintenance of fax machines" },
  { text: "95125 - Repair and maintenance of communications transmission equipment" },
  { text: "95126 - Repair and maintenance of two-way radios" },
  { text: "95127 - Repair and maintenance of commercial TV and video cameras" },
  { text: "95211 - Repair and maintenance of television, radio receivers" },
  { text: "95212 - Repair and maintenance of VCR/DVD/VCD" },
  { text: "95213 - Repair and maintenance of CD players" },
  { text: "95214 - Repair and maintenance of household-type video cameras" },
  { text: "95221 - Repair and servicing of household appliances" },
  { text: "95222 - Repair and servicing of home and garden equipment" },
  { text: "95230 - Repair of footwear and leather goods" },
  { text: "95240 - Repair of furniture and home furnishings" },
  { text: "95291 - Repair of bicycles" },
  { text: "95292 - Repair and alteration of clothing" },
  { text: "95293 - Repair and alteration of jewellery" },
  { text: "95294 - Repair of watches, clocks and their parts" },
  { text: "95295 - Repair of sporting goods" },
  { text: "95296 - Repair of musical instruments" },
  { text: "95299 - Repair of other personal and household goods n.e.c." },
  { text: "96011 - Laundering and dry-cleaning, pressing" },
  { text: "96012 - Carpet and ruq shampooing, and drapery and curtain cleaning, whether on clients' premises or not" },
  { text: "96013 - Provision of linens, work uniforms and related items by laundries" },
  { text: "96014 - Diaper supply services" },
  { text: "96020 - Hairdressing and other beauty treatment" },
  { text: "96031 - Preparing the dead for burial or cremation and embalming and morticians' services" },
  { text: "96032 - Providing burial or cremation services" },
  { text: "96033 - Rental of equipped space in funeral parlours" },
  { text: "96034 - Rental or sale of graves" },
  { text: "96035 - Maintenance of graves and mausoleums" },
  { text: "96091 - Activities of sauna, steam baths, massage salons" },
  { text: "96092 - Astrological and spiritualists' activities" },
  { text: "96093 - Social activities such as escort services, dating services, services of marriage bureaux" },
  { text: "96094 - Pet care services" },
  { text: "96095 - Genealogical organizations" },
  { text: "96096 - Shoe shiners, porters, valet car parkers" },
  { text: "96097 - Concession operation of coin-operated personal service machines" },
  { text: "96099 - Other service activities n.e.c." },
  { text: "97000 - Activities of households as employers of domestic personnel" },
  { text: "98100 - Undifferentiated goods-producing activities of private households for own use" },
  { text: "98200 - Undifferentiated service-producing activities of private households for own use" },
  { text: "99000 - Activities of extraterritorial organization and bodies" }
]

let optionsMsic = msic.map(code => `<option value="${code.value}">${code.value}</option>`).join('\n');
let lastMsicSelect, directorCountrySelect, directorCountrySelectLast;
function mapDirectorCountrySelect() {
  directorCountrySelect = document.querySelectorAll('select[data-select-type="director-country"]');
  lastDirectorSelect = directorCountrySelect.length - 1;
  directorCountrySelectLast = directorCountrySelect[lastDirectorSelect];
  directorCountrySelectLast.innerHTML = options;
}
mapDirectorCountrySelect();

function getMsicCodes() {
	// let request = new XMLHttpRequest();
	// let url = new URL('https://api.centry.digital/api:8ppyfTOI/msic_code')
  // request.open('GET', url, true);
	// request.onload = function() {
  // 	if (request.status >=200 && request.status < 400) {
  //   	var data = JSON.parse(this.response);
  //   }
		var select = new SlimSelect({
  		select: '#msic-codes',
   		limit: 3,
    	data: msic,
      onChange: (selections) => {
				incorporationSummary.msicCodes = [];
        for (const selection of selections){
					incorporationSummary.msicCodes.push(selection.value);
				}
				validateInput();
				if (incorporationSummary.msicCodes != "") {
					document.querySelector(".ss-multi-selected").classList.remove("invalid-field");
				} else {
					document.querySelector(".ss-multi-selected").classList.add("invalid-field");
				}
		  }
		})
	}
	request.send();
  
(function() {
	getMsicCodes();
})();